### ISSUE TITLE
[Suggestion] New Language

### ISSUE THREAD

**Issue by DeskTecc** [AlphaOmega-IT/AOCommands#1]
Hello i'm Tecc and i want to contribute this plugin with a translation i've made of my native language: **Brazilian Portuguese**.

[language_ptBR.zip](https://github.com/AlphaOmega-IT/AOCommands/files/9890468/language_ptBR.zip)

Thanks :)

**Comment by AlphaOmega-IT** [comment]
Hey! Sure, give me a few minutes. I will add this file. I appreciate your help!

**Comment by AlphaOmega-IT** [comment]
Added going to deploy the newest Language version. Added you as Contributor in the file, and at the spigot mc update.
